KW-MUJI/BE

README.md
src/main/resources/application.properties

1. README 수정 - 커밋컨벤션 추가
2. applications.properties 파일 삭제
close #1

docs/chore: README 수정 & properties 파일 삭제

---

src/main/java/com/muji_backend/kw_muji/common/entity/ParticipationEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/ProjectEntity.java

1. resumePath 컬럼을 project 테이블에서 participation 테이블로 이동
close #9

fix: resumePath 컬럼 위치 변경

---

src/main/java/com/muji_backend/kw_muji/common/entity/QuestionEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/ResponseEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/SurveyEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/UserEntity.java
src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/SurveyResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/repository/SurveyRepository.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveyService.java

1. 검색어 필터링
2. 게시글 페이징처리
close #16

feat: 설문조사 메인 게시글 페이지

---

src/main/java/com/muji_backend/kw_muji/common/entity/SurveyEntity.java
src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/dto/request/SurveyRequestDto.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/SurveyResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/repository/ChoiceRepository.java
src/main/java/com/muji_backend/kw_muji/survey/repository/QuestionRepository.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveyService.java

1. 설문조사 게시글 생성 기능
2. questionType에 따라 다르게 저장
close #23

feat: 설문조사 게시글 생성 기능

---

src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/SurveyDetailResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveyService.java

1. 설문조사 세부정보 조회 기능 구현
-> 서비스 로직 리팩토링 필요

feat: 설문조사 세부정보 조회 기능

---

src/main/java/com/muji_backend/kw_muji/kwnotice/controller/NoticeController.java
src/main/java/com/muji_backend/kw_muji/kwnotice/repository/NoticeRepository.java
src/main/java/com/muji_backend/kw_muji/kwnotice/repository/NoticeRepositoryImpl.java
src/main/java/com/muji_backend/kw_muji/kwnotice/service/NoticeService.java
src/main/java/com/muji_backend/kw_muji/kwnotice/service/NoticeServiceImpl.java
src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveyCreateService.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveyService.java

1. 설문조사 관련 클래스 분리 및 각 메서드 로직 메서드 분리
2. 생성자 주입 방법 RequiredArgsConstructor로 변경
close #25

refactor: 설문조사 관련 메서드 리팩토링 

---

src/main/java/com/muji_backend/kw_muji/common/entity/AnswerEntity.java
src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/dto/request/SurveySubmitRequestDto.java
src/main/java/com/muji_backend/kw_muji/survey/repository/AnswerRepository.java
src/main/java/com/muji_backend/kw_muji/survey/repository/ResponseRepository.java
src/main/java/com/muji_backend/kw_muji/survey/service/SurveySubmitService.java

1. 설문 참여 api crud 설계
2. AnswerEntity의 choiceId의 nullable 설정 true로 설정
3. QuestionType에 따라 테이블 설정 로직 설계
close #28

feat: 설문 참여 기능

---

src/main/java/com/muji_backend/kw_muji/survey/controller/MySurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/service/MySurveyService.java

1. 설문조사 진행 종료 기능
2. 설문조사 삭제 기능
close #34

feat: 설문 상태 변경 및 삭제 기능

---

src/main/java/com/muji_backend/kw_muji/survey/controller/MySurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/MySurveyResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/MySurveyResultResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/SurveyDetailResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/dto/response/SurveyResponseDto.java
src/main/java/com/muji_backend/kw_muji/survey/repository/ResponseRepository.java
src/main/java/com/muji_backend/kw_muji/survey/service/MySurveyService.java

1. 설문조사 결과 조회 기능 추가
2. 기존의 세부정보 조회 서비스 활용
close #36

feat: 설문조사 결과 조회 기능

---

src/main/java/com/muji_backend/kw_muji/common/config/SwaggerConfig.java
src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

1. swaggerConfig에 시큐리티 설정 추가
2. security에 스웨거 진입 경로 열어두기
close #42

feat: swagger, security 추가

---

src/main/java/com/muji_backend/kw_muji/calendar/dto/request/CalendarRequestDto.java

1. calendar request dto userId 삭제
close: #56

fix: calendar request dto delete userId

---

src/main/java/com/muji_backend/kw_muji/KwMujiApplication.java
src/main/java/com/muji_backend/kw_muji/survey/repository/SurveyRepository.java
src/main/java/com/muji_backend/kw_muji/survey/scheduling/SurveyScheduledTask.java

1. 설문조사의 isOngoing을 매일 자정마다 스케쥴링을 통해 업데이트
close: #38

feat: 설문조사 스케쥴링 설정

---

src/main/java/com/muji_backend/kw_muji/survey/repository/SurveyRepository.java
src/main/java/com/muji_backend/kw_muji/survey/scheduling/SurveyScheduledTask.java

1. cron 시간 수정, jpa 메서드 수정
close: #73

fix: cron, jpa 수정

---

src/main/java/com/muji_backend/kw_muji/calendar/dto/response/CalendarResponseDto.java
src/main/java/com/muji_backend/kw_muji/mainpage/controller/MainController.java
src/main/java/com/muji_backend/kw_muji/mainpage/dto/response/MainResponseDto.java
src/main/java/com/muji_backend/kw_muji/mainpage/service/MainService.java

1. 메인페이지 공지사항, 설문조사, 캘린더 조회 기능
2. 로그인 여부에 따라 조회
close #75

feat: mainpage function

---

src/main/java/com/muji_backend/kw_muji/calendar/controller/CalendarController.java
src/main/java/com/muji_backend/kw_muji/calendar/dto/response/CalendarResponseDto.java
src/main/java/com/muji_backend/kw_muji/calendar/repository/ParticipationRepository.java
src/main/java/com/muji_backend/kw_muji/calendar/repository/UserCalendarRepository.java
src/main/java/com/muji_backend/kw_muji/calendar/service/CalendarService.java
src/main/java/com/muji_backend/kw_muji/survey/controller/MySurveyController.java
src/main/java/com/muji_backend/kw_muji/survey/controller/SurveyController.java

1. 캘린더 ui 변경 사항에 맞춰 기능 수정
2. 팀플 일정 추가 및 삭제 시 팀원의 일정 동기화
close #86 #87

feat/fix: 캘린더 변경 사항에 맞춰 수정 & 팀플 일정 동기화

---

src/test/java/com/muji_backend/kw_muji/calendar/service/CalendarServiceTest.java

- 같은 팀플에 참여하고 있고 같은 제목, 같은 일정이라도, 목적이 다른 팀플은 삭제되면 안됨
- 이를 역 검증하는 테스트 코드 작성
- 모두 삭제되는 문제 확인
- user 테이블 userCalendar 테이블을 다대다 연결로 바꿔야 함
close #92

test(CalendarService): 팀플 일정 삭제 문제 통합 단위 테스트 추가

---

src/main/java/com/muji_backend/kw_muji/calendar/repository/UserCalendarRepository.java
src/main/java/com/muji_backend/kw_muji/calendar/repository/UserEventLinkRepository.java
src/main/java/com/muji_backend/kw_muji/calendar/service/CalendarService.java
src/main/java/com/muji_backend/kw_muji/common/entity/ProjectEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/UserCalendarEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/UserEntity.java
src/main/java/com/muji_backend/kw_muji/common/entity/UserEventLinkEntity.java
src/test/java/com/muji_backend/kw_muji/calendar/service/CalendarServiceTest.java

1. project, user / usercalendar 테이블 간 다대다 관계를 만들어야 하므로 중개 테이블 생성
2. 수정된 erd에 맞게 팀플 일정을 공통 추가할때, 하나의 일정에 대해서 여러 팀원들이 공유하도록 수정
3. 링크 삭제 테스트 코드 작성
close: #94

fix/test: 93pr 문제 해결을 위해 ERD 엔티티 구조 수정 및 테스트 코드 수정

---

src/main/java/com/muji_backend/kw_muji/mypage/controller/MypageController.java
src/main/java/com/muji_backend/kw_muji/mypage/dto/response/MyResponseDTO.java
src/main/java/com/muji_backend/kw_muji/mypage/service/MypageService.java

1. mySurvey 기능을 이용하여 설문조사 기능 연결
2. my팀플, my모집 팀플, my 설문 정보 반환 dto 설정
close: #96

feat: mypage 설문 기능 및 dto 설정

---

src/main/java/com/muji_backend/kw_muji/mypage/controller/MypageController.java
src/main/java/com/muji_backend/kw_muji/mypage/dto/response/MyResponseDTO.java
src/main/java/com/muji_backend/kw_muji/mypage/service/MypageService.java

1. 최신 my 팀플 4개 조회
2. 최신 my 모집 팀플 4개 조회
3. 최신 my 설문 4개 조회
4. dto 설정 및 비즈니스 로직 구현
close: #99

feat: mypage 메인 화면 기능 추가

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java
src/main/java/com/muji_backend/kw_muji/kwnotice/controller/NoticeController.java
src/main/java/com/muji_backend/kw_muji/kwnotice/repository/NoticeRepositoryImpl.java

- 인증 없이 접근 가능 경로 추가
- 공지사항 오류 수정
close: #106

feat(cors): 경로 인가 추가 및 공지사항 기능 수정(#106)

---

src/main/java/com/muji_backend/kw_muji/common/config/RedisConfig.java

- ec2 배포를 위해 redisConfig 설정
close #108

feat(redis): redisConfig 추가

---

.gitignore
appspec.yml
deploy.sh
docker/Dockerfile

1. Dockerfile 추가
2. deploy.sh 추가
3. appspec.yml 추가

cicd: 배포 관련 파일 추가

---

.github/workflows/deploy.yml

cicd: deploy.yml 수정(#112)

---

scripts/deploy.sh

cicd: deploy.sh 수정(#112)

---

appspec.yml
scripts/deploy.sh

cicd: ec2 소유자 변경

---

scripts/deploy.sh

cicd: deploy.sh 수정

---

scripts/deploy.sh

cicd: docker-compose 스크립트 수정(#112)

---

scripts/deploy.sh

cicd: docker-compose 스크립트 수정

---

docker/docker-compose.blue.yml
docker/docker-compose.green.yml
scripts/deploy.sh

1. docker-compose version 삭제
- 참고 도커 공식 문서: https://docs.docker.com/reference/compose-file/version-and-name/
2. deploy.sh 수정

cicd: docker-compose version 삭제 및 deploy.sh 수정

---

docker/Dockerfile

cicd: Dockerfile 수정

---

.github/workflows/deploy.yml

cicd: 배포 테스트

---

docker/docker-compose.blue.yml
docker/docker-compose.green.yml

cicd: docker-compose 수정

---

.github/workflows/build.yml
.github/workflows/deploy.yml

배포 전, main 및 develop 브랜치에서 정상적으로 build가 되는지 테스트하는 과정

cicd: add build.yml

---

.github/workflows/build.yml
.github/workflows/deploy.yml
README.md

workflow 수정
1. environment 추가
2. JDK의 distribution을 temurin으로 수정(속도 향상 목적)
close: #137

cicd: deploy yml fix

---

src/main/java/com/muji_backend/kw_muji/team/controller/MyTeamController.java
src/main/java/com/muji_backend/kw_muji/team/service/MyTeamService.java
src/main/java/com/muji_backend/kw_muji/team/service/TeamService.java

MY 모집 팀플에서 팀 프로젝트 시작 Btn 기능 개발

feat : 팀프로젝트 시작

---

src/main/java/com/muji_backend/kw_muji/calendar/dto/request/CalendarRequestDto.java
src/main/java/com/muji_backend/kw_muji/calendar/dto/response/CalendarResponseDto.java
src/main/java/com/muji_backend/kw_muji/common/entity/UserEventLinkEntity.java
src/main/java/com/muji_backend/kw_muji/team/service/MyTeamService.java

1. datetime을 모두 yyyy-MM-dd HH:mm:ss 형식으로 수정
2. UserEventLinkEntity에서 projectId를 null 허용

fix: 캘린더 기능 수정

---

src/main/java/com/muji_backend/kw_muji/mypage/dto/request/UpdateRequestDTO.java
src/main/java/com/muji_backend/kw_muji/mypage/dto/response/MyResponseDTO.java
src/main/java/com/muji_backend/kw_muji/survey/scheduling/SurveyScheduledTask.java
src/main/java/com/muji_backend/kw_muji/team/dto/request/ProjectDetailRequestDTO.java
src/main/java/com/muji_backend/kw_muji/team/dto/response/MyCreatedProjectResponseDTO.java
src/main/java/com/muji_backend/kw_muji/team/dto/response/ProjectDetailResponseDTO.java
src/main/java/com/muji_backend/kw_muji/team/dto/response/ProjectListResponseDTO.java
src/main/java/com/muji_backend/kw_muji/team/scheduling/TeamSchefuledTask.java

1. LocalDateTime를 yyyy-MM-dd HH:mm:ss로 명시
2. Dto의 is를 포함하는 변수들 is 포함해서 명시

fix: LocalDateTime 명시 및 Dto is 명시

---

docker/docker-compose.blue.yml
docker/docker-compose.green.yml
src/main/java/com/muji_backend/kw_muji/survey/scheduling/SurveyScheduledTask.java
src/main/java/com/muji_backend/kw_muji/team/repository/TeamRepository.java
src/main/java/com/muji_backend/kw_muji/team/scheduling/TeamScheduledTask.java

fix: 도커 컴포즈 수정 및 크론식 테스트 배포

---

src/main/java/com/muji_backend/kw_muji/survey/scheduling/SurveyScheduledTask.java
src/main/java/com/muji_backend/kw_muji/team/scheduling/TeamScheduledTask.java

- 배포 환경에서 스케쥴링 성공했으므로 크론식 자정 시간을 수정

fix: 테스트 통과 크론식 자정 수정

---

src/main/java/com/muji_backend/kw_muji/calendar/service/CalendarService.java

- filter를 통해 동일 팀플 팀원의 일정 중복 조회 문제 해결
close: #190

fix: 팀플 일정 중복 조회 수정

---

src/main/java/com/muji_backend/kw_muji/common/entity/ProjectEntity.java
src/main/java/com/muji_backend/kw_muji/team/controller/TeamController.java

- 글쓰기 최대 글자수 약 10000자로 증설
- 글쓰기 요청 파라미터에서 바디 형식으로 변경
close: #193

fix: 글쓰기 최대 글자 수 변경 & 요청 형식 변경

---

src/main/java/com/muji_backend/kw_muji/calendar/service/CalendarService.java
src/main/java/com/muji_backend/kw_muji/common/entity/ProjectEntity.java
src/main/java/com/muji_backend/kw_muji/team/controller/TeamController.java

- 글쓰기 최대 글자수 약 10000자로 증설
- 글쓰기 요청 파라미터에서 바디 형식으로 변경

fix: 팀플 글쓰기 기능 수

---

src/main/java/com/muji_backend/kw_muji/team/controller/TeamController.java
src/main/java/com/muji_backend/kw_muji/team/dto/request/RegisterRequestDTO.java

이미지 업로드 문제를 @ModelAttribute를 활용하여 해결
close: #196

fix: 이미지 업로드 수정

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

fix: cors 경로 추가

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

fix: cors 설정 수정

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

fix: cors 설정 변경

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

fix: cors 변경

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java

fix: cors 추가

---

src/main/java/com/muji_backend/kw_muji/common/controller/HealthController.java

feat: health 컨트롤러 추가

---

src/main/java/com/muji_backend/kw_muji/common/config/WebConfig.java
src/main/java/com/muji_backend/kw_muji/mypage/service/MypageService.java
src/main/java/com/muji_backend/kw_muji/team/service/MyTeamService.java

fix: png 업로드 가능

---

src/main/java/com/muji_backend/kw_muji/common/security/TokenProvider.java

test: token 만료 시간 변경

---

src/main/java/com/muji_backend/kw_muji/common/security/TokenProvider.java

test: 토큰 만료 시간 원상복구
